; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][version] = "3.0-beta3"

projects[addressfield][version] = "1.0-beta2"

projects[admin][version] = "2.x-dev"

projects[admin_menu][version] = "3.0-rc1"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "2.2"

projects[service_links][version] = "2.1"

projects[blockreference][version] = "1.9"

projects[ctools][version] = "1.0-rc1"

projects[calendar][version] = "3.0-alpha1"

projects[fontyourface][version] = "1.6"

projects[content_taxonomy][version] = "1.0-beta1"

projects[date][version] = "2.0-alpha5"

projects[devel][version] = "1.2"

projects[disqus][version] = "1.9"

projects[entity][version] = "1.x-dev"

projects[features][version] = "1.0-beta4"

projects[field_collection][subdir] = "field"
projects[field_collection][version] = "1.x-dev"

projects[field_group][subdir] = "field"
projects[field_group][version] = "1.1"

projects[file_entity][version] = "2.0-unstable2"

projects[globalredirect][version] = "1.4"

projects[internal_nodes][version] = "1.1"

projects[jquery_update][version] = "2.x-dev"

projects[link][version] = "1.0"

projects[mailchimp][version] = "1.0"

projects[media][version] = "2.x-dev"

projects[media_youtube][version] = "1.0-alpha5"

projects[menu_block][version] = "2.2"

projects[references][version] = "2.0-beta3"

projects[office_hours][version] = "1.x-dev"

projects[panelizer][version] = "2.0-rc1+1-dev"

projects[panels][version] = "3.0-alpha3"

projects[pathauto][version] = "1.0"

projects[strongarm][version] = "2.0-beta4"

projects[token][version] = "1.0-beta7"

projects[views][version] = "3.0-rc3"

projects[webform][version] = "3.13"

projects[wysiwyg][version] = "2.1"

; Themes
projects[adaptivetheme][version] = "2.1"

projects[footheme][version] = "2.0"

projects[genesis][subdir] = "genesis"
projects[genesis][version] = "2.x-dev"

projects[rubik][version] = "4.0-beta6"

projects[sky][version] = "2.2"

projects[tao][version] = "3.0-beta4"

projects[cpn][type] = "module"
projects[cpn][download][type] = "git"
projects[cpn][download][url] = "http://git.drupal.org/project/cpn.git"
projects[cpn][download][branch] = "7.x-1.x"
projects[cpn][download][revision] = "83241885ee57b904e0eff8a05169baec7d0e3244"
