; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc1"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[service_links][subdir] = "contrib"
projects[service_links][version] = "2.1"

projects[blockreference][subdir] = "contrib"
projects[blockreference][version] = "1.9"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.0-rc1"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.0-alpha2"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "1.6"

projects[content_taxonomy][subdir] = "contrib"
projects[content_taxonomy][version] = "1.0-beta1"

projects[date][subdir] = "contrib"
projects[date][version] = "2.0-rc2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc1+29-dev"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0-beta6"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta3"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable3"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.x-dev"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.1+7-dev"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.x-dev"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[mailchimp][subdir] = "contrib"
projects[mailchimp][version] = "1.0"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.2"

projects[references][subdir] = "contrib"
projects[references][version] = "2.0"

projects[office_hours][subdir] = "contrib"
projects[office_hours][version] = "1.x-dev"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "2.0-rc1+1-dev"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.0"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0-beta4"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-rc1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.1"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.13"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.1"

; Themes
projects[adaptivetheme][subdir] = "contrib"
projects[adaptivetheme][version] = "2.1"

projects[footheme][subdir] = "contrib"
projects[footheme][version] = "2.0"

projects[rubik][subdir] = "contrib"
projects[rubik][version] = "4.0-beta6"

projects[sky][subdir] = "contrib"
projects[sky][version] = "2.2"

projects[tao][subdir] = "contrib"
projects[tao][version] = "3.0-beta4"

; Modules
projects[autocreate][type] = "module"
projects[autocreate][download][type] = "git"
projects[autocreate][download][url] = "http://git.drupal.org/project/autocreate.git"
projects[autocreate][download][revision] = "f3f38dddd720f288bb1ee9aaad879420329c9e3b"

projects[cpn][type] = "module"
projects[cpn][download][type] = "git"
projects[cpn][download][url] = "http://git.drupal.org/project/cpn.git"
projects[cpn][download][branch] = "7.x-1.x"
projects[cpn][download][revision] = "83241885ee57b904e0eff8a05169baec7d0e3244"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%203.6.2%20for%20Drupal/ckeditor_3.6.2_for_drupal_7.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

libraries[json2.js][download][type] = "git"
libraries[json2.js][download][url] = "https://github.com/douglascrockford/JSON-js.git"
libraries[json2.js][directory_name] = "json2.js"
libraries[json2.js][type] = "library"

